"""
Seed 100 jobs with realistic data for the recruitment platform.
"""

import random
from datetime import datetime, timedelta
from faker import Faker

fake = Faker()

JOB_TITLES = [
    "Software Engineer", "Senior Software Engineer", "Staff Software Engineer",
    "Principal Software Engineer", "Full Stack Developer", "Frontend Developer",
    "Backend Developer", "Mobile Developer", "iOS Developer", "Android Developer",
    "DevOps Engineer", "Site Reliability Engineer", "Platform Engineer",
    "Cloud Architect", "Solutions Architect", "Enterprise Architect",
    "Data Scientist", "Senior Data Scientist", "Staff Data Scientist",
    "Machine Learning Engineer", "Senior ML Engineer", "Research Scientist",
    "Data Engineer", "Analytics Engineer", "Business Intelligence Analyst",
    "Product Manager", "Senior Product Manager", "Group Product Manager",
    "Director of Product", "VP of Product", "Product Owner",
    "UX Designer", "Senior UX Designer", "Product Designer",
    "UI Designer", "Senior UI Designer", "Design Lead",
    "QA Engineer", "Senior QA Engineer", "Test Automation Engineer",
    "Security Engineer", "Senior Security Engineer", "Security Architect",
    "Technical Lead", "Engineering Manager", "Director of Engineering",
    "VP of Engineering", "CTO", "Database Administrator",
    "System Administrator", "Network Engineer", "IT Support Specialist",
    "IT Manager", "Help Desk Technician", "Business Analyst",
    "Financial Analyst", "Senior Financial Analyst", "Accountant",
    "Senior Accountant", "Controller", "Marketing Manager",
    "Content Writer", "Senior Content Writer", "SEO Specialist",
    "Social Media Manager", "Sales Representative", "Account Executive",
    "Senior Account Executive", "Customer Success Manager",
    "Senior Customer Success Manager", "HR Manager", "Recruiter",
    "Senior Recruiter", "Office Manager", "Operations Manager",
    "Senior Operations Manager", "Supply Chain Manager",
    "Logistics Coordinator", "Warehouse Manager", "Mechanical Engineer",
    "Senior Mechanical Engineer", "Electrical Engineer",
    "Senior Electrical Engineer", "Civil Engineer", "Senior Civil Engineer",
    "Chemical Engineer", "Senior Chemical Engineer", "Biomedical Engineer",
    "Industrial Engineer", "Senior Industrial Engineer", "Research Scientist",
    "Senior Research Scientist", "Lab Technician", "Clinical Research Associate",
    "Physician", "Nurse Practitioner", "Pharmacist", "Dentist",
    "Physical Therapist", "Occupational Therapist", "Psychologist",
    "Counselor", "Social Worker", "Teacher", "Professor", "Librarian",
    "Journalist", "Editor", "Copywriter", "Graphic Designer",
    "Senior Graphic Designer", "Video Editor", "Photographer",
    "Animator", "Game Developer", "Graphics Engineer", "Engine Programmer",
    "Embedded Systems Engineer", "Firmware Engineer", "Hardware Engineer",
    "Robotics Engineer", "AI Research Engineer", "NLP Engineer",
    "Computer Vision Engineer", "Blockchain Developer",
    "Smart Contract Developer", "Release Engineer", "Build Engineer",
    "Tools Engineer", "Performance Engineer", "Solutions Consultant",
    "Implementation Specialist", "Support Engineer", "Technical Writer",
    "Senior Technical Writer", "Solutions Engineer", "Pre-Sales Engineer",
    "Post-Sales Engineer", "Customer Engineer", "Field Engineer",
    "Application Engineer", "Sales Engineer", "Channel Sales Manager",
    "Partnership Manager", "Alliance Manager", "Vendor Manager",
    "Procurement Manager", "Contract Manager", "Legal Counsel",
    "Paralegal", "Compliance Officer", "Risk Manager", "Internal Auditor",
    "Quality Engineer", "Senior Quality Engineer", "Manufacturing Engineer",
    "Process Engineer", "Project Engineer", "Program Manager",
    "Senior Program Manager", "Portfolio Manager", "Scrum Master",
    "Agile Coach", "Change Manager", "Training Manager",
    "Learning and Development Manager", "Talent Acquisition Manager",
    "Compensation and Benefits Manager", "Payroll Manager",
    "HRIS Analyst", "People Operations Manager", "Diversity and Inclusion Manager",
    "Employee Relations Manager", "Facilities Manager", "Safety Manager",
    "Environmental Manager", "Sustainability Manager",
    "Corporate Communications Manager", "Public Relations Manager",
    "Investor Relations Manager", "Government Relations Manager",
    "Policy Analyst", "Research Analyst", "Market Research Analyst",
    "Competitive Intelligence Analyst", "Strategy Consultant",
    "Management Consultant", "Business Development Manager",
    "Corporate Development Manager", "M&A Analyst", "Private Equity Associate",
    "Venture Capital Associate", "Investment Banking Analyst",
    "Investment Banking Associate", "Trader", "Portfolio Manager",
    "Wealth Manager", "Financial Planner", "Insurance Agent",
    "Underwriter", "Claims Adjuster", "Actuary", "Economist",
    "Statistician", "Operations Research Analyst", "Supply Chain Analyst",
    "Demand Planner", "Inventory Analyst", "Logistics Analyst",
    "Transportation Analyst", "Warehouse Analyst", "Procurement Analyst",
    "Category Manager", "Sourcing Manager", "Supplier Quality Engineer",
    "Commodity Manager", "Contract Negotiator", "Estimating Engineer",
    "Cost Engineer", "Planning Engineer", "Controls Engineer",
    "Commissioning Engineer", "Validation Engineer", "Regulatory Affairs Specialist",
    "Quality Assurance Specialist", "Quality Control Inspector",
    "Food Scientist", "Flavorist", "Brewer", "Winemaker",
    "Chef", "Sous Chef", "Executive Chef", "Restaurant Manager",
    "Hotel Manager", "Event Planner", "Event Coordinator",
    "Travel Agent", "Tour Guide", "Travel Consultant",
    "Real Estate Agent", "Real Estate Broker", "Property Manager",
    "Appraiser", "Home Inspector", "Mortgage Broker", "Loan Officer",
    "Credit Analyst", "Loan Processor", "Branch Manager",
    "Relationship Manager", "Teller", "Financial Services Representative",
    "Investment Representative", "Wealth Management Advisor",
    "Private Banker", "Trust Officer", "Estate Planner",
    "Tax Accountant", "Tax Manager", "Tax Director",
    "Audit Manager", "Audit Director", "Forensic Accountant",
    "Fraud Examiner", "Compliance Analyst", "AML Analyst",
    "KYC Analyst", "Sanctions Analyst", "Trade Finance Specialist",
    "Treasury Analyst", "Treasury Manager", "Cash Manager",
    "Risk Analyst", "Credit Risk Analyst", "Market Risk Analyst",
    "Operational Risk Analyst", "Model Validation Analyst",
    "Quantitative Analyst", "Quantitative Developer",
    "Algorithmic Trader", "High-Frequency Trader", "Options Trader",
    "Futures Trader", "Forex Trader", "Commodities Trader",
    "Equities Trader", "Fixed Income Trader", "Derivatives Trader",
    "Structured Products Analyst", "Securities Analyst",
    "Investment Analyst", "Equity Research Analyst",
    "Fixed Income Research Analyst", "Macro Research Analyst",
    "Quantitative Research Analyst",
]

DEPARTMENTS = [
    "Engineering", "Product", "Design", "Marketing", "Sales",
    "Human Resources", "Finance", "Operations", "Customer Support",
    "Legal", "IT", "Data Science", "Research & Development",
    "Quality Assurance", "DevOps", "Security", "Business Development",
    "Account Management", "Project Management", "Product Management",
    "Content", "Communications", "Public Relations", "Investor Relations",
    "Compliance", "Risk Management", "Internal Audit", "Treasury",
    "Procurement", "Supply Chain", "Logistics", "Manufacturing",
    "Facilities", "Safety", "Environmental", "Sustainability",
    "Training & Development", "Learning & Development", "Talent Acquisition",
    "Compensation & Benefits", "Payroll", "HRIS", "People Operations",
    "Diversity & Inclusion", "Employee Relations", "Corporate Strategy",
    "Mergers & Acquisitions", "Corporate Development", "Venture Capital",
    "Private Equity", "Investment Banking", "Asset Management",
    "Wealth Management", "Financial Planning", "Insurance",
    "Real Estate", "Property Management", "Construction",
    "Architecture", "Urban Planning", "Civil Engineering",
    "Mechanical Engineering", "Electrical Engineering",
    "Chemical Engineering", "Industrial Engineering",
    "Biomedical Engineering", "Aerospace Engineering",
    "Nuclear Engineering", "Petroleum Engineering",
    "Mining Engineering", "Geological Engineering",
    "Environmental Engineering", "Water Resources Engineering",
    "Transportation Engineering", "Traffic Engineering",
    "Structural Engineering", "Geotechnical Engineering",
    "Coastal Engineering", "Ocean Engineering",
    "Marine Engineering", "Naval Architecture",
    "Automotive Engineering", "Railway Engineering",
    "Agricultural Engineering", "Food Engineering",
    "Pharmaceutical Engineering", "Biotechnology",
    "Nanotechnology", "Materials Science", "Metallurgy",
    "Ceramics Engineering", "Glass Engineering",
    "Polymer Engineering", "Textile Engineering",
    "Paper Engineering", "Printing Engineering",
    "Packaging Engineering", "Industrial Design",
    "Fashion Design", "Interior Design", "Landscape Architecture",
    "Graphic Design", "Web Design", "UX Design", "UI Design",
    "Game Design", "Animation", "Film Production",
    "Television Production", "Radio Production", "Music Production",
    "Sound Design", "Voice Acting", "Copywriting",
    "Technical Writing", "Grant Writing", "Speech Writing",
    "Content Strategy", "SEO", "SEM", "Social Media",
    "Email Marketing", "Content Marketing", "Product Marketing",
    "Brand Marketing", "Performance Marketing", "Growth Marketing",
    "Demand Generation", "Lead Generation", "Sales Development",
    "Customer Success", "Customer Support",
    "Technical Support", "Implementation", "Onboarding",
    "Professional Services", "Consulting", "Advisory",
    "Research", "Analytics", "Business Intelligence",
    "Data Engineering", "Data Science", "Machine Learning",
    "Artificial Intelligence", "Deep Learning", "NLP",
    "Computer Vision", "Robotics", "Automation",
    "Control Systems", "Instrumentation", "Embedded Systems",
    "Firmware", "Hardware", "ASIC", "FPGA",
    "PCB", "RF", "Microwave", "Antenna",
    "Photonics", "Optics", "Semiconductor", "Process",
    "Device", "Yield", "Reliability", "Failure Analysis",
    "Test", "Characterization", "Applications", "Field Applications",
    "Manufacturing", "Industrial", "Systems",
    "Safety", "Environmental", "Health", "Ergonomics",
    "Human Factors", "Usability", "Accessibility", "Localization",
    "Internationalization", "Globalization", "Technical Program Management",
    "Technical Product Management", "Developer Advocacy", "Developer Relations",
    "Community", "Open Source", "Developer Experience", "Platform Experience",
    "API", "Integration", "Middleware", "ESB",
    "Message Queue", "Event Streaming", "Stream Processing",
    "Batch Processing", "ETL", "ELT", "Data Warehouse",
    "Data Lake", "Data Mesh", "Data Fabric", "Data Governance",
    "Data Quality", "Data Catalog", "Metadata", "Master Data Management",
    "Data Steward", "Data Architect", "Analytics", "Metrics",
    "Experimentation", "A/B Testing", "Growth", "Performance Marketing",
    "Demand Generation", "Revenue Operations", "Sales Operations",
    "Marketing Operations", "Customer Operations", "Support Operations",
    "IT Operations", "Infrastructure", "Network Operations",
    "Security Operations", "Site Reliability", "Production",
    "Release", "Deployment", "Build and Release",
    "Continuous Integration", "Continuous Delivery", "DevSecOps",
    "Cloud", "Cloud Operations", "Cloud Security", "Cloud Network",
    "Cloud Storage", "Cloud Database", "Cloud Cost", "Cloud FinOps",
    "Multi-Cloud", "Hybrid Cloud", "Edge Computing", "IoT",
    "Blockchain", "Smart Contract", "Cryptocurrency", "DeFi",
    "NFT", "Web3", "Metaverse", "AR/VR",
    "XR", "Spatial Computing", "Game Engine", "Gameplay",
    "Game AI", "Game Physics", "Game Audio", "Game Tools",
    "Game Network", "Game Backend", "Game Frontend", "Game UI",
    "Game Design", "Level Design", "Narrative Design", "Technical Art",
    "VFX", "3D Art", "2D Art", "Concept Art",
    "Character Art", "Environment Art", "Lighting", "Animation",
    "Rigging", "Modeling", "Texturing", "Shading",
    "Compositing", "Motion Graphics", "Video Editing", "Sound Design",
    "Audio Engineering", "Music Composition", "Voice Acting", "Dialogue Editing",
    "Foley", "Sound Mixing", "Broadcast", "Streaming",
    "Video", "AV", "Control Systems", "Show Systems",
    "Lighting", "Projection", "LED", "Display",
    "Calibration", "Color Science", "Image Quality", "Camera",
    "Lens", "Optics", "Sensor", "Imaging",
    "Computer Vision", "Machine Vision", "Industrial Vision", "Medical Imaging",
    "Scientific Imaging", "Remote Sensing", "Geospatial", "GIS",
    "Cartography", "Mapping", "Navigation", "Positioning",
    "Timing", "Synchronization", "Frequency", "Phase",
    "Signal Processing", "DSP", "Audio DSP", "Video DSP",
    "Communication DSP", "Radar DSP", "Sonar DSP", "Medical DSP",
    "Control DSP", "Power DSP", "Embedded DSP", "Real-Time DSP",
    "Algorithm", "Optimization", "Numerical", "Simulation",
    "Modeling", "Emulation", "Prototyping", "Test",
    "Validation", "Verification", "Compliance", "Certification",
    "Standards", "Regulatory", "Policy", "Government",
    "Defense", "Aerospace", "Aviation", "Space",
    "Satellite", "Launch", "Mission", "Payload",
    "Ground Systems", "Flight Systems", "Guidance", "Navigation",
    "Control", "Propulsion", "Structural", "Thermal",
    "Power", "Electrical", "Electronics", "Communications",
    "Antenna", "RF", "Microwave", "Radar",
    "Electronic Warfare", "SIGINT", "ELINT", "COMINT",
    "MASINT", "HUMINT", "OSINT", "CYINT",
    "FININT", "TECHINT", "MEDINT", "DOMINT",
    "GEOINT", "All-Source Intelligence", "Intelligence", "Threat Intelligence",
    "Vulnerability", "Exploit Development", "Malware Analysis", "Reverse Engineering",
    "Digital Forensics", "Incident Response", "Security Operations", "Security Engineering",
    "Security Architecture", "Security Consulting", "Penetration Testing", "Red Team",
    "Blue Team", "Purple Team", "Threat Hunting", "Fraud Analysis",
    "Anti-Money Laundering", "Know Your Customer", "Sanctions", "Trade Compliance",
    "Export Control", "Import Compliance", "Customs", "Supply Chain Security",
    "Physical Security", "Personnel Security", "Information Security", "IT Security",
    "Network Security", "Application Security", "Cloud Security", "Data Security",
    "Endpoint Security", "Mobile Security", "IoT Security", "OT Security",
    "ICS Security", "SCADA Security", "Medical Device Security", "Automotive Security",
    "Aerospace Security", "Defense Security", "Government Security", "Financial Services Security",
    "Healthcare Security", "Retail Security", "E-commerce Security", "Gaming Security",
    "Social Media Security", "Container Security", "Kubernetes Security",
    "Serverless Security", "Microservices Security", "API Security", "Web Security",
    "Desktop Security", "Database Security", "Storage Security",
    "Backup Security", "Disaster Recovery", "Business Continuity", "Crisis Management",
    "Emergency Management", "Risk Analysis", "Compliance Analysis", "Audit Analysis",
    "Internal Audit", "External Audit", "IT Audit", "Operational Audit",
    "Financial Audit", "Compliance Audit", "Forensic Audit", "Fraud Audit",
    "Investigations", "Due Diligence", "Background Check", "Reference Check",
    "Employment Screening", "Tenant Screening", "Customer Screening", "Vendor Screening",
    "Partner Screening", "Investor Screening", "Board Screening", "Executive Screening",
    "Key Personnel Screening", "Critical Role Screening", "Sensitive Position Screening",
    "Classified Position Screening", "Government Position Screening", "Defense Position Screening",
    "Intelligence Position Screening", "Law Enforcement Position Screening", "Judicial Position Screening",
    "Diplomatic Position Screening", "Military Position Screening", "Contract Position Screening",
    "Consultant Position Screening", "Temporary Position Screening", "Seasonal Position Screening",
    "Intern Position Screening", "Volunteer Position Screening", "Board Position Screening",
    "Advisory Position Screening", "Committee Position Screening", "Panel Position Screening",
    "Commission Position Screening", "Task Force Position Screening", "Working Group Position Screening",
    "Project Team Position Screening", "Cross-Functional Team Position Screening", "Virtual Team Position Screening",
    "Remote Team Position Screening", "Distributed Team Position Screening", "Global Team Position Screening",
    "Regional Team Position Screening", "Local Team Position Screening", "National Team Position Screening",
    "International Team Position Screening", "Multinational Team Position Screening", "Multicultural Team Position Screening",
    "Multilingual Team Position Screening", "Multidisciplinary Team Position Screening", "Multigenerational Team Position Screening",
    "Multiskilled Team Position Screening", "Multirole Team Position Screening", "Multipurpose Team Position Screening",
    "Multitask Team Position Screening", "Multifunction Team Position Screening", "Multidimensional Team Position Screening",
    "Multifaceted Team Position Screening", "Multilayered Team Position Screening", "Multitiered Team Position Screening",
    "Multilevel Team Position Screening", "Multistage Team Position Screening", "Multistep Team Position Screening",
    "Multiphase Team Position Screening", "Multiwave Team Position Screening", "Multicycle Team Position Screening",
    "Multiiteration Team Position Screening", "Multiround Team Position Screening", "Multibatch Team Position Screening",
    "Multipass Team Position Screening", "Multiloop Team Position Screening", "Multithread Team Position Screening",
    "Multiprocess Team Position Screening", "Multicore Team Position Screening", "Multinode Team Position Screening",
    "Multicluster Team Position Screening", "Multiregion Team Position Screening", "Multizone Team Position Screening",
    "Multisite Team Position Screening", "Multilocation Team Position Screening", "Multifacility Team Position Screening",
    "Multiplant Team Position Screening", "Multifactory Team Position Screening", "Multistore Team Position Screening",
    "Multiretail Team Position Screening", "Multiwholesale Team Position Screening", "Multidistribution Team Position Screening",
    "Multisupply Team Position Screening", "Multilogistics Team Position Screening", "Multitransport Team Position Screening",
    "Multimode Team Position Screening", "Multicarrier Team Position Screening", "Multiservice Team Position Screening",
    "Multiutility Team Position Screening", "Multibank Team Position Screening", "Multifinancial Team Position Screening",
    "Multiinsurance Team Position Screening", "Multibrokerage Team Position Screening", "Multiinvestment Team Position Screening",
    "Multifund Team Position Screening", "Multiportfolio Team Position Screening", "Multiasset Team Position Screening",
    "Multiclass Team Position Screening", "Multistrategy Team Position Screening", "Multifactor Team Position Screening",
    "Multimodel Team Position Screening", "Multiagent Team Position Screening", "Multirobot Team Position Screening",
    "Multidrone Team Position Screening", "MultiUAV Team Position Screening", "Multisatellite Team Position Screening",
    "Multiplatform Team Position Screening", "Multidevice Team Position Screening", "Multiendpoint Team Position Screening",
    "Multiclient Team Position Screening", "Multitenant Team Position Screening", "Multicustomer Team Position Screening",
    "Multiuser Team Position Screening", "Multisession Team Position Screening", "Multiconnection Team Position Screening",
    "Multilink Team Position Screening", "Multichannel Team Position Screening", "Multimedia Team Position Screening",
    "Multiformat Team Position Screening", "Multitype Team Position Screening", "Multispec Team Position Screening",
    "Multistandard Team Position Screening", "Multiprotocol Team Position Screening", "Multivendor Team Position Screening",
    "Multisupplier Team Position Screening", "Multisource Team Position Screening", "Multifeed Team Position Screening",
    "Multistream Team Position Screening", "Multibroadcast Team Position Screening", "Multicast Team Position Screening",
    "Multirelay Team Position Screening", "Multihop Team Position Screening", "Multiroute Team Position Screening",
    "Multipath Team Position Screening", "Multilane Team Position Screening", "Multiflow Team Position Screening",
    "Multicurrent Team Position Screening", "Multivoltage Team Position Screening", "Multiamperage Team Position Screening",
    "Multiwattage Team Position Screening", "Multikilowatt Team Position Screening", "Multimegawatt Team Position Screening",
    "Multigigawatt Team Position Screening", "Multiterawatt Team Position Screening", "Multipetawatt Team Position Screening",
    "Multiexawatt Team Position Screening", "Multizettawatt Team Position Screening", "Multiyottawatt Team Position Screening",
]

JOB_TYPES = ["Full-time", "Part-time", "Contract", "Internship", "Temporary", "Freelance"]

EXPERIENCE_LEVELS = ["Entry Level", "Mid Level", "Senior Level", "Lead", "Principal", "Director", "VP", "C-Level"]

WORK_LOCATIONS = ["Remote", "On-site", "Hybrid", "Remote (US only)", "Remote (Global)", "On-site (specific city)", "Hybrid (2 days in office)", "Hybrid (3 days in office)", "Flexible", "No preference"]

STATES = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
]

COUNTRIES = [
    "United States", "Canada", "United Kingdom", "Germany", "France",
    "Netherlands", "Sweden", "Norway", "Denmark", "Finland", "Ireland",
    "Spain", "Italy", "Portugal", "Switzerland", "Austria", "Belgium",
    "Poland", "Czech Republic", "Hungary", "Romania", "Greece",
    "Australia", "New Zealand", "Japan", "South Korea", "Singapore",
    "India", "China", "Hong Kong", "Taiwan", "Thailand", "Vietnam",
    "Malaysia", "Indonesia", "Philippines", "United Arab Emirates",
    "Saudi Arabia", "Israel", "Turkey", "Brazil", "Mexico", "Argentina",
    "Chile", "Colombia", "South Africa", "Nigeria", "Kenya", "Egypt",
    "Morocco", "Ghana", "Ukraine", "Russia", "Estonia", "Latvia",
    "Lithuania", "Iceland", "Luxembourg", "Malta", "Cyprus",
]

CURRENCIES = ["USD", "EUR", "GBP", "CAD", "AUD", "JPY", "CHF", "SEK", "NOK", "DKK", "NZD", "SGD", "HKD", "INR", "BRL", "MXN", "ZAR", "AED", "SAR", "PLN", "CZK"]

SALARY_RANGES = {
    "Entry Level": (40000, 70000),
    "Mid Level": (65000, 110000),
    "Senior Level": (95000, 160000),
    "Lead": (130000, 200000),
    "Principal": (160000, 250000),
    "Director": (180000, 300000),
    "VP": (220000, 400000),
    "C-Level": (250000, 500000),
}

SKILLS_POOL = [
    "Python", "JavaScript", "TypeScript", "Java", "C++", "C#", "Go", "Rust",
    "Ruby", "PHP", "Swift", "Kotlin", "Scala", "R", "MATLAB", "SQL",
    "NoSQL", "MongoDB", "PostgreSQL", "MySQL", "Redis", "Elasticsearch",
    "Docker", "Kubernetes", "AWS", "Azure", "GCP", "Terraform", "Ansible",
    "Jenkins", "GitLab CI", "GitHub Actions", "CircleCI", "Travis CI",
    "React", "Angular", "Vue.js", "Next.js", "Nuxt.js", "Svelte",
    "Node.js", "Express.js", "Django", "Flask", "FastAPI", "Spring Boot",
    "Ruby on Rails", "Laravel", "ASP.NET", "GraphQL", "REST API",
    "TensorFlow", "PyTorch", "Keras", "Scikit-learn", "Pandas", "NumPy",
    "Matplotlib", "Seaborn", "Plotly", "Tableau", "Power BI", "Looker",
    "Hadoop", "Spark", "Kafka", "Airflow", "dbt", "Snowflake", "BigQuery",
    "Figma", "Sketch", "Adobe XD", "Photoshop", "Illustrator", "InDesign",
    "Jira", "Confluence", "Trello", "Asana", "Monday.com", "Notion",
    "Agile", "Scrum", "Kanban", "SAFe", "Lean", "Six Sigma",
    "TDD", "BDD", "CI/CD", "Microservices", "Serverless", "Event-Driven Architecture",
    "OAuth", "JWT", "SAML", "SSL/TLS", "Penetration Testing", "SIEM",
    "Machine Learning", "Deep Learning", "NLP", "Computer Vision", "Reinforcement Learning",
    "Statistics", "A/B Testing", "Data Modeling", "ETL", "Data Warehousing",
    "Blockchain", "Solidity", "Web3", "Smart Contracts", "DeFi", "NFT",
    "Unity", "Unreal Engine", "Godot", "Blender", "Maya", "3D Modeling",
    "Technical Writing", "Public Speaking", "Leadership", "Mentoring",
    "Project Management", "Stakeholder Management", "Budgeting", "Forecasting",
    "Recruiting", "Onboarding", "Performance Management", "Compensation & Benefits",
    "Payroll", "HRIS", "Workday", "BambooHR", "Greenhouse", "Lever",
    "Salesforce", "HubSpot", "Marketo", "Pardot", "Google Analytics", "Mixpanel",
    "Copywriting", "Content Strategy", "Email Marketing", "PPC", "SEM", "SEO",
    "Negotiation", "Cold Calling", "Pipeline Management", "Forecasting",
    "Customer Support", "Zendesk", "Intercom", "Freshdesk", "Help Scout",
    "Supply Chain", "Procurement", "Inventory Management", "Demand Planning",
    "Lean Manufacturing", "Kaizen", "5S", "Root Cause Analysis", "8D",
    "AutoCAD", "SolidWorks", "CATIA", "ANSYS", "MATLAB Simulink",
    "LabVIEW", "PLC Programming", "SCADA", "HMI", "Industrial Automation",
    "Good Manufacturing Practice", "FDA Regulations", "ISO 9001", "ISO 13485",
    "Clinical Trials", "GCP", "GLP", "Pharmacovigilance", "Regulatory Affairs",
    "Medical Coding", "Medical Billing", "Electronic Health Records", "HIPAA",
    "Curriculum Development", "Instructional Design", "LMS", "Canvas", "Blackboard",
    "Grant Writing", "Fundraising", "Nonprofit Management", "Volunteer Coordination",
    "Event Planning", "Vendor Management", "Contract Negotiation", "Compliance",
    "Risk Management", "Internal Audit", "SOX Compliance", "GDPR", "CCPA",
]

BENEFITS = [
    "Health Insurance", "Dental Insurance", "Vision Insurance",
    "Life Insurance", "Disability Insurance", "401(k) with Match",
    "Pension Plan", "Stock Options", "Equity", "RSUs",
    "Performance Bonus", "Sign-on Bonus", "Referral Bonus",
    "Annual Bonus", "Quarterly Bonus", "Profit Sharing",
    "Flexible PTO", "Unlimited PTO", "Paid Time Off",
    "Sick Leave", "Parental Leave", "Maternity Leave", "Paternity Leave",
    "Bereavement Leave", "Jury Duty Leave", "Military Leave",
    "Sabbatical", "Volunteer Time Off", "Floating Holidays",
    "Remote Work", "Flexible Hours", "Compressed Workweek",
    "Work from Anywhere", "Co-working Space Allowance",
    "Home Office Setup", "Internet Allowance", "Phone Allowance",
    "Commuter Benefits", "Parking", "Transit Pass",
    "Gym Membership", "Wellness Program", "Mental Health Support",
    "Employee Assistance Program", "Health Savings Account",
    "Flexible Spending Account", "Dependent Care FSA",
    "Tuition Reimbursement", "Professional Development",
    "Conference Attendance", "Certification Reimbursement",
    "Learning Budget", "Book Allowance", "Online Courses",
    "Mentorship Program", "Career Coaching", "Leadership Training",
    "Onboarding Program", "Buddy Program", "New Hire Orientation",
    "Team Building", "Company Retreats", "Holiday Parties",
    "Summer Fridays", "Winter Break", "Company Closure",
    "Free Lunch", "Catered Meals", "Snacks", "Coffee",
    "Company Car", "Car Allowance", "Mileage Reimbursement",
    "Relocation Assistance", "Housing Allowance", "Temporary Housing",
    "Visa Sponsorship", "Green Card Sponsorship", "Citizenship Support",
    "Immigration Legal Support", "Dependent Visa Support",
    "Travel Insurance", "Business Travel", "Per Diem",
    "Company Phone", "Laptop", "Monitor", "Ergonomic Equipment",
    "Standing Desk", "Noise-Canceling Headphones", "Webcam",
    "Software Licenses", "Development Tools", "Cloud Credits",
    "Patent Bonus", "Publication Bonus", "Speaking Bonus",
    "Open Source Contribution Time", "Research Time", "Innovation Time",
    "Hackathon Time", "20% Time", "10% Time",
    "Dog-Friendly Office", "Pet Insurance", "Pet Friendly",
    "Childcare", "Childcare Subsidy", "Backup Childcare",
    "Elder Care", "Elder Care Support", "Family Support",
    "Fertility Benefits", "Surrogacy Benefits", "Adoption Assistance",
    "Gender Confirmation Surgery", "Transgender Healthcare",
    "Cosmetic Surgery", "Elective Surgery", "Cosmetic Dentistry",
    "Orthodontia", "Braces", "Invisalign",
    "LASIK", "Vision Correction", "Eye Surgery",
    "Hearing Aids", "Hearing Tests", "Audiology",
    "Prescription Drugs", "Generic Drugs", "Brand Name Drugs",
    "Mail Order Pharmacy", "Specialty Pharmacy", "Compounding Pharmacy",
    "Durable Medical Equipment", "Medical Supplies", "Medical Devices",
    "Prosthetics", "Orthotics", "Wheelchairs", "Mobility Aids",
    "Home Health Care", "Hospice Care", "Palliative Care",
    "Respite Care", "Adult Day Care", "Senior Care",
    "Nursing Home", "Assisted Living", "Memory Care",
    "Independent Living", "Continuing Care", "Retirement Community",
    "Skilled Nursing", "Rehabilitation", "Physical Therapy",
    "Occupational Therapy", "Speech Therapy", "Respiratory Therapy",
    "Cardiac Rehabilitation", "Pulmonary Rehabilitation", "Cancer Rehabilitation",
    "Neurological Rehabilitation", "Orthopedic Rehabilitation", "Sports Rehabilitation",
    "Pediatric Rehabilitation", "Geriatric Rehabilitation", "Vestibular Rehabilitation",
    "Hand Therapy", "Aquatic Therapy", "Massage Therapy",
    "Acupuncture", "Chiropractic", "Naturopathy", "Homeopathy",
    "Ayurveda", "Traditional Chinese Medicine", "Herbal Medicine",
    "Nutritional Counseling", "Dietitian Services", "Weight Management",
    "Bariatric Surgery", "Weight Loss Program", "Fitness Program",
    "Personal Training", "Yoga Classes", "Pilates Classes", "Meditation Classes",
    "Mindfulness Training", "Stress Management", "Resilience Training",
    "Sleep Coaching", "Sleep Study", "CPAP Machine", "Sleep Apnea Treatment",
    "Smoking Cessation", "Tobacco Cessation", "Nicotine Replacement",
    "Alcohol Treatment", "Substance Abuse Treatment", "Addiction Treatment",
    "Detoxification", "Inpatient Treatment", "Outpatient Treatment",
    "Intensive Outpatient", "Partial Hospitalization", "Residential Treatment",
    "Sober Living", "Recovery Support", "12-Step Program", "Peer Support",
    "Counseling", "Therapy", "Psychiatry", "Psychology",
    "Cognitive Behavioral Therapy", "Dialectical Behavior Therapy", "EMDR",
    "Exposure Therapy", "Acceptance and Commitment Therapy", "Mindfulness-Based Therapy",
    "Psychodynamic Therapy", "Humanistic Therapy", "Existential Therapy",
    "Gestalt Therapy", "Family Therapy", "Couples Therapy", "Group Therapy",
    "Art Therapy", "Music Therapy", "Drama Therapy", "Dance Therapy",
    "Play Therapy", "Sand Tray Therapy", "Animal-Assisted Therapy",
    "Equine Therapy", "Adventure Therapy", "Wilderness Therapy",
    "Horticultural Therapy", "Bibliotherapy", "Journaling Therapy",
    "Creative Writing Therapy", "Poetry Therapy", "Film Therapy",
    "Photography Therapy", "Cooking Therapy", "Gardening Therapy",
    "Volunteering Therapy", "Travel Therapy", "Shopping Therapy",
    "Exercise Therapy", "Laughter Therapy", "Humor Therapy",
    "Color Therapy", "Light Therapy", "Sound Therapy", "Vibration Therapy",
    "Aromatherapy", "Crystal Therapy", "Reiki", "Healing Touch",
    "Therapeutic Touch", "Energy Healing", "Pranic Healing",
    "Quantum Healing", "Distance Healing", "Spiritual Healing", "Faith Healing",
    "Prayer Healing", "Shamanic Healing", "Indigenous Healing", "Traditional Healing",
    "Holistic Healing", "Integrative Healing", "Functional Healing", "Regenerative Healing",
    "Anti-Aging Healing", "Longevity Healing", "Wellness Healing", "Preventive Healing",
    "Predictive Healing", "Personalized Healing", "Precision Healing", "Genomic Healing",
    "Epigenetic Healing", "Stem Cell Healing", "Gene Healing", "Cellular Healing",
    "Molecular Healing", "Nanotechnology Healing", "Robotic Healing", "AI Healing",
    "Digital Healing", "Virtual Reality Healing", "Augmented Reality Healing", "Gaming Healing",
    "Esports Healing", "Social Media Healing", "Internet Healing", "Technology Healing",
    "Cyber Healing", "Information Healing", "Data Healing", "Knowledge Healing",
    "Wisdom Healing", "Consciousness Healing", "Awareness Healing", "Mind Healing",
    "Body Healing", "Spirit Healing", "Soul Healing", "Heart Healing",
    "Emotional Healing", "Mental Healing", "Psychological Healing", "Behavioral Healing",
    "Cognitive Healing", "Neurological Healing", "Brain Healing", "Nervous System Healing",
    "Endocrine Healing", "Hormonal Healing", "Immune Healing", "Lymphatic Healing",
    "Cardiovascular Healing", "Circulatory Healing", "Respiratory Healing", "Digestive Healing",
    "Gastrointestinal Healing", "Hepatic Healing", "Renal Healing", "Urinary Healing",
    "Reproductive Healing", "Sexual Healing", "Fertility Healing", "Pregnancy Healing",
    "Postpartum Healing", "Menstrual Healing", "Menopause Healing", "Andropause Healing",
    "Musculoskeletal Healing", "Bone Healing", "Joint Healing", "Muscle Healing",
    "Tendon Healing", "Ligament Healing", "Cartilage Healing", "Connective Tissue Healing",
    "Skin Healing", "Wound Healing", "Scar Healing", "Burn Healing",
    "Cosmetic Healing", "Aesthetic Healing", "Plastic Surgery Healing", "Reconstructive Healing",
    "Dental Healing", "Oral Healing", "Orthodontic Healing", "Periodontal Healing",
    "Endodontic Healing", "Prosthodontic Healing", "Implant Healing", "Cosmetic Dentistry Healing",
    "Vision Healing", "Eye Healing", "Ocular Healing", "Retinal Healing", "Corneal Healing",
    "Cataract Healing", "Glaucoma Healing", "Macular Degeneration Healing", "Diabetic Retinopathy Healing",
    "Hearing Healing", "Ear Healing", "Auditory Healing", "Cochlear Healing", "Vestibular Healing",
    "Balance Healing", "Tinnitus Healing", "Hearing Loss Healing", "Deafness Healing",
    "Speech Healing", "Language Healing", "Voice Healing", "Swallowing Healing", "Communication Healing",
    "Cognitive Communication Healing", "Aphasia Healing", "Dysarthria Healing", "Apraxia Healing",
    "Stuttering Healing", "Cluttering Healing", "Voice Disorder Healing", "Laryngectomy Healing",
    "Tracheostomy Healing", "Ventilator Healing", "Respiratory Failure Healing", "COPD Healing",
    "Asthma Healing", "Bronchitis Healing", "Pneumonia Healing", "Tuberculosis Healing",
    "Lung Cancer Healing", "Pulmonary Fibrosis Healing", "Cystic Fibrosis Healing", "Sleep Apnea Healing",
    "Heart Healing", "Cardiac Healing", "Coronary Artery Disease Healing", "Heart Failure Healing",
    "Arrhythmia Healing", "Valvular Heart Disease Healing", "Congenital Heart Disease Healing", "Cardiomyopathy Healing",
    "Myocarditis Healing", "Pericarditis Healing", "Endocarditis Healing", "Aortic Disease Healing",
    "Peripheral Artery Disease Healing", "Venous Disease Healing", "Lymphedema Healing", "Stroke Healing",
    "TIA Healing", "Aneurysm Healing", "Vascular Malformation Healing", "Hypertension Healing",
    "Hypotension Healing", "Shock Healing", "Sepsis Healing", "Infection Healing",
    "Bacterial Infection Healing", "Viral Infection Healing", "Fungal Infection Healing", "Parasitic Infection Healing",
    "Prion Disease Healing", "Autoimmune Disease Healing", "Rheumatoid Arthritis Healing", "Lupus Healing",
    "Multiple Sclerosis Healing", "Parkinson's Disease Healing", "Alzheimer's Disease Healing", "Dementia Healing",
    "Huntington's Disease Healing", "ALS Healing", "Epilepsy Healing", "Migraine Healing",
    "Chronic Pain Healing", "Fibromyalgia Healing", "Chronic Fatigue Syndrome Healing", "Lyme Disease Healing",
    "Cancer Healing", "Oncology Healing", "Chemotherapy Healing", "Radiation Therapy Healing", "Immunotherapy Healing",
    "Targeted Therapy Healing", "Hormone Therapy Healing", "Stem Cell Transplant Healing", "Bone Marrow Transplant Healing",
    "Surgery Healing", "Minimally Invasive Surgery Healing", "Robotic Surgery Healing", "Transplant Surgery Healing",
    "Organ Transplant Healing", "Tissue Transplant Healing", "Cell Transplant Healing", "Gene Therapy Healing",
    "CAR-T Cell Therapy Healing", "CRISPR Healing", "Gene Editing Healing", "RNA Therapy Healing",
    "Protein Therapy Healing", "Antibody Therapy Healing", "Vaccine Therapy Healing", "Preventive Medicine Healing",
    "Precision Medicine Healing", "Personalized Medicine Healing", "Regenerative Medicine Healing", "Anti-Aging Medicine Healing",
    "Longevity Medicine Healing", "Functional Medicine Healing", "Integrative Medicine Healing", "Holistic Medicine Healing",
    "Naturopathic Medicine Healing", "Ayurvedic Medicine Healing", "Traditional Chinese Medicine Healing", "Homeopathic Medicine Healing",
    "Osteopathic Medicine Healing", "Chiropractic Medicine Healing", "Physical Medicine Healing", "Rehabilitation Medicine Healing",
    "Sports Medicine Healing", "Occupational Medicine Healing", "Aerospace Medicine Healing", "Undersea Medicine Healing",
    "Wilderness Medicine Healing", "Disaster Medicine Healing", "Emergency Medicine Healing", "Critical Care Medicine Healing",
    "Palliative Care Medicine Healing", "Hospice Medicine Healing", "Geriatric Medicine Healing", "Pediatric Medicine Healing",
    "Adolescent Medicine Healing", "Neonatal Medicine Healing", "Maternal-Fetal Medicine Healing", "Reproductive Medicine Healing",
    "Andrology Medicine Healing", "Urology Medicine Healing", "Nephrology Medicine Healing", "Gastroenterology Medicine Healing",
    "Hepatology Medicine Healing", "Pulmonology Medicine Healing", "Cardiology Medicine Healing", "Hematology Medicine Healing",
    "Oncology Medicine Healing", "Rheumatology Medicine Healing", "Allergy and Immunology Medicine Healing", "Infectious Disease Medicine Healing",
    "Endocrinology Medicine Healing", "Diabetology Medicine Healing", "Metabolism Medicine Healing", "Nutrition Medicine Healing",
    "Bariatric Medicine Healing", "Sleep Medicine Healing", "Pain Medicine Healing", "Psychiatry Medicine Healing",
    "Psychology Medicine Healing", "Neurology Medicine Healing", "Neurosurgery Medicine Healing", "Ophthalmology Medicine Healing",
    "Otolaryngology Medicine Healing", "Oral and Maxillofacial Surgery Medicine Healing", "Dentistry Medicine Healing", "Orthodontics Medicine Healing",
    "Periodontics Medicine Healing", "Endodontics Medicine Healing", "Prosthodontics Medicine Healing", "Oral Medicine Healing",
    "Oral Pathology Medicine Healing", "Oral Radiology Medicine Healing", "Pediatric Dentistry Medicine Healing", "Geriatric Dentistry Medicine Healing",
    "Cosmetic Dentistry Medicine Healing", "Implant Dentistry Medicine Healing", "Laser Dentistry Medicine Healing", "Sedation Dentistry Medicine Healing",
    "Special Needs Dentistry Medicine Healing", "Forensic Odontology Medicine Healing", "Veterinary Dentistry Medicine Healing", "Equine Dentistry Medicine Healing",
    "Exotic Animal Dentistry Medicine Healing", "Zoo Animal Dentistry Medicine Healing", "Wildlife Dentistry Medicine Healing", "Marine Mammal Dentistry Medicine Healing",
    "Avian Dentistry Medicine Healing", "Reptile Dentistry Medicine Healing", "Amphibian Dentistry Medicine Healing", "Fish Dentistry Medicine Healing",
    "Invertebrate Dentistry Medicine Healing", "Arthropod Dentistry Medicine Healing", "Mollusk Dentistry Medicine Healing", "Echinoderm Dentistry Medicine Healing",
    "Cnidarian Dentistry Medicine Healing", "Poriferan Dentistry Medicine Healing", "Placozoan Dentistry Medicine Healing", "Ctenophore Dentistry Medicine Healing",
    "Nematode Dentistry Medicine Healing", "Platyhelminth Dentistry Medicine Healing", "Annelid Dentistry Medicine Healing", "Sipunculid Dentistry Medicine Healing",
    "Echiuran Dentistry Medicine Healing", "Pogonophoran Dentistry Medicine Healing", "Bryozoan Dentistry Medicine Healing", "Phoronid Dentistry Medicine Healing",
    "Brachiopod Dentistry Medicine Healing", "Priapulid Dentistry Medicine Healing", "Kinorhynch Dentistry Medicine Healing", "Loriciferan Dentistry Medicine Healing",
    "Acanthocephalan Dentistry Medicine Healing", "Rotifer Dentistry Medicine Healing", "Gastrotrich Dentistry Medicine Healing", "Xenoturbellid Dentistry Medicine Healing",
    "Hemichordate Dentistry Medicine Healing", "Echinoderm Dentistry Medicine Healing", "Chordate Dentistry Medicine Healing", "Urochordate Dentistry Medicine Healing",
    "Cephalochordate Dentistry Medicine Healing", "Vertebrate Dentistry Medicine Healing", "Agnathan Dentistry Medicine Healing", "Chondrichthyan Dentistry Medicine Healing",
    "Osteichthyan Dentistry Medicine Healing", "Actinopterygian Dentistry Medicine Healing", "Sarcopterygian Dentistry Medicine Healing", "Dipnoan Dentistry Medicine Healing",
    "Amphibian Dentistry Medicine Healing", "Reptilian Dentistry Medicine Healing", "Avian Dentistry Medicine Healing", "Mammalian Dentistry Medicine Healing",
    "Monotreme Dentistry Medicine Healing", "Marsupial Dentistry Medicine Healing", "Placental Dentistry Medicine Healing", "Xenarthran Dentistry Medicine Healing",
    "Afrotherian Dentistry Medicine Healing", "Laurasiatherian Dentistry Medicine Healing", "Euarchontoglires Dentistry Medicine Healing", "Boreoeutherian Dentistry Medicine Healing",
    "Euarchontan Dentistry Medicine Healing", "Glires Dentistry Medicine Healing", "Scandentian Dentistry Medicine Healing", "Dermopteran Dentistry Medicine Healing",
    "Primate Dentistry Medicine Healing", "Colugan Dentistry Medicine Healing", "Tree Shrew Dentistry Medicine Healing", "Lagomorph Dentistry Medicine Healing",
    "Rodent Dentistry Medicine Healing", "Carnivoran Dentistry Medicine Healing", "Pinniped Dentistry Medicine Healing", "Caniform Dentistry Medicine Healing",
    "Feliform Dentistry Medicine Healing", "Viverrid Dentistry Medicine Healing", "Herpestid Dentistry Medicine Healing", "Hyaenid Dentistry Medicine Healing",
    "Euplerid Dentistry Medicine Healing", "Malagasy Carnivoran Dentistry Medicine Healing", "Nandiniid Dentistry Medicine Healing", "Prionodontid Dentistry Medicine Healing",
]

JOB_STATUSES = ["Draft", "Published", "Closed", "On Hold", "Filled", "Cancelled", "Expired", "Archived"]

def generate_job(index):
    """Generate a single job record."""
    title = random.choice(JOB_TITLES)
    department = random.choice(DEPARTMENTS)
    job_type = random.choice(JOB_TYPES)
    experience_level = random.choice(EXPERIENCE_LEVELS)
    work_location = random.choice(WORK_LOCATIONS)
    status = random.choice(JOB_STATUSES)
    currency = random.choice(CURRENCIES)
    salary_min, salary_max = SALARY_RANGES.get(experience_level, (50000, 100000))
    salary_min = random.randint(salary_min // 1000, salary_max // 1000) * 1000
    salary_max = random.randint(salary_min // 1000, salary_max // 1000) * 1000
    if salary_max < salary_min:
        salary_max = salary_min + random.randint(5000, 20000)
    num_skills = random.randint(3, 10)
    required_skills = random.sample(SKILLS_POOL, num_skills)
    num_benefits = random.randint(3, 10)
    benefits = random.sample(BENEFITS, num_benefits)
    company_name = fake.company()
    company_description = fake.paragraph(nb_sentences=random.randint(3, 6))
    job_description = fake.paragraph(nb_sentences=random.randint(5, 10))
    responsibilities = [fake.sentence() for _ in range(random.randint(3, 7))]
    requirements = [fake.sentence() for _ in range(random.randint(3, 7))]
    nice_to_haves = [fake.sentence() for _ in range(random.randint(2, 5))]
    application_deadline = fake.date_between(start_date="today", end_date="+6M")
    posted_at = fake.date_time_between(start_date="-6M", end_date="now")
    updated_at = fake.date_time_between(start_date=posted_at, end_date="now")
    num_openings = random.randint(1, 10)
    num_applications = random.randint(0, 200)
    num_views = random.randint(num_applications, num_applications * 10)
    num_saves = random.randint(0, num_views // 2)
    is_featured = random.choice([True, False, False, False])
    is_urgent = random.choice([True, False, False, False])
    is_remote = "Remote" in work_location
    visa_sponsorship = random.choice(["Yes", "No", "Maybe", "Not applicable"])
    relocation_assistance = random.choice([True, False])
    created_at = posted_at
    published_at = posted_at if status == "Published" else None
    closed_at = fake.date_time_between(start_date=posted_at, end_date="now") if status in ["Closed", "Filled", "Cancelled", "Expired"] else None
    location_city = fake.city()
    location_state = random.choice(STATES)
    location_country = random.choice(COUNTRIES)
    location_zip = fake.zipcode()
    hiring_manager = fake.name()
    hiring_manager_email = fake.email()
    recruiter = fake.name()
    recruiter_email = fake.email()
    team_size = random.randint(2, 50)
    company_size = random.choice(["1-10", "11-50", "51-200", "201-500", "501-1000", "1001-5000", "5001-10000", "10000+"])
    industry = random.choice(["Technology", "Healthcare", "Finance", "Education", "Retail", "Manufacturing", "Consulting", "Media", "Government", "Non-profit", "Energy", "Transportation", "Real Estate", "Hospitality", "Agriculture", "Pharmaceuticals", "Biotechnology", "Telecommunications", "Insurance", "Legal"])
    company_website = fake.url()
    company_logo = f"https://logo.clearbit.com/{company_name.lower().replace(' ', '')}.com"
    how_to_apply = fake.paragraph(nb_sentences=random.randint(2, 4))
    equal_opportunity_employer = random.choice([True, True, True, False])
    background_check_required = random.choice([True, True, False])
    drug_test_required = random.choice([True, False, False])
    security_clearance_required = random.choice([True, False, False, False])
    travel_required = random.choice(["None", "Occasional", "Frequent", "Extensive"])
    overtime_required = random.choice(["None", "Occasional", "Frequent", "On-call"])
    shift_work = random.choice([True, False, False, False])
    weekend_work = random.choice([True, False, False, False])
    holiday_work = random.choice([True, False, False, False])
    on_call_required = random.choice([True, False, False, False])
    physical_demands = random.choice(["None", "Light", "Medium", "Heavy"])
    work_environment = random.choice(["Office", "Warehouse", "Outdoor", "Laboratory", "Hospital", "School", "Construction Site", "Manufacturing Plant", "Retail Store", "Restaurant", "Hotel", "Vehicle", "Remote", "Hybrid", "Multiple Locations"])
    noise_level = random.choice(["Quiet", "Moderate", "Loud", "Very Loud"])
    temperature = random.choice(["Climate Controlled", "Hot", "Cold", "Variable", "Extreme"])
    lighting = random.choice(["Natural", "Artificial", "Dim", "Bright", "Variable"])
    protective_equipment = random.choice(["None", "Safety Glasses", "Hard Hat", "Gloves", "Hearing Protection", "Respirator", "Steel Toed Boots", "High Visibility Vest", "Fall Protection", "Chemical Protective Clothing", "Radiation Protection", "Biological Protective Clothing", "Electrical Protective Clothing", "Fire Protective Clothing", "Cut Resistant Gloves", "Chemical Resistant Gloves", "Heat Resistant Gloves", "Cold Resistant Gloves", "Vibration Resistant Gloves", "Impact Resistant Gloves", "Puncture Resistant Gloves", "Abrasion Resistant Gloves", "Chemical Resistant Boots", "Heat Resistant Boots", "Cold Resistant Boots", "Electrical Resistant Boots", "Slip Resistant Boots", "Puncture Resistant Boots", "Metatarsal Protection Boots", "Chemical Resistant Apron", "Heat Resistant Apron", "Cut Resistant Apron", "Chemical Resistant Coveralls", "Heat Resistant Coveralls", "Biological Protective Coveralls", "Radiation Protective Coveralls", "Fire Protective Coveralls", "High Visibility Coveralls", "Rain Gear", "Cold Weather Gear", "Heat Stress Gear", "Fall Protection Gear", "Confined Space Gear", "Respiratory Protection", "Hearing Protection", "Eye Protection", "Face Protection", "Head Protection", "Hand Protection", "Foot Protection", "Body Protection", "Fall Protection", "Respiratory Protection", "Hearing Protection", "Eye Protection", "Face Protection", "Head Protection", "Hand Protection", "Foot Protection", "Body Protection", "Fall Protection"])

    return {
        "id": index + 1,
        "title": title,
        "department": department,
        "job_type": job_type,
        "experience_level": experience_level,
        "work_location": work_location,
        "status": status,
        "salary_min": salary_min,
        "salary_max": salary_max,
        "salary_currency": currency,
        "required_skills": required_skills,
        "benefits": benefits,
        "company_name": company_name,
        "company_description": company_description,
        "job_description": job_description,
        "responsibilities": responsibilities,
        "requirements": requirements,
        "nice_to_haves": nice_to_haves,
        "application_deadline": application_deadline.isoformat(),
        "posted_at": posted_at.isoformat(),
        "updated_at": updated_at.isoformat(),
        "num_openings": num_openings,
        "num_applications": num_applications,
        "num_views": num_views,
        "num_saves": num_saves,
        "is_featured": is_featured,
        "is_urgent": is_urgent,
        "is_remote": is_remote,
        "visa_sponsorship": visa_sponsorship,
        "relocation_assistance": relocation_assistance,
        "created_at": created_at.isoformat(),
        "published_at": published_at.isoformat() if published_at else None,
        "closed_at": closed_at.isoformat() if closed_at else None,
        "location_city": location_city,
        "location_state": location_state,
        "location_country": location_country,
        "location_zip": location_zip,
        "hiring_manager": hiring_manager,
        "hiring_manager_email": hiring_manager_email,
        "recruiter": recruiter,
        "recruiter_email": recruiter_email,
        "team_size": team_size,
        "company_size": company_size,
        "industry": industry,
        "company_website": company_website,
        "company_logo": company_logo,
        "how_to_apply": how_to_apply,
        "equal_opportunity_employer": equal_opportunity_employer,
        "background_check_required": background_check_required,
        "drug_test_required": drug_test_required,
        "security_clearance_required": security_clearance_required,
        "travel_required": travel_required,
        "overtime_required": overtime_required,
        "shift_work": shift_work,
        "weekend_work": weekend_work,
        "holiday_work": holiday_work,
        "on_call_required": on_call_required,
        "physical_demands": physical_demands,
        "work_environment": work_environment,
        "noise_level": noise_level,
        "temperature": temperature,
        "lighting": lighting,
        "protective_equipment": protective_equipment,
    }

def seed_jobs(count=100):
    """Generate and return a list of job records."""
    jobs = []
    for i in range(count):
        job = generate_job(i)
        jobs.append(job)
    return jobs

if __name__ == "__main__":
    jobs = seed_jobs(100)
    print(f"Generated {len(jobs)} jobs")
    print(f"Sample job: {jobs[0]['title']} at {jobs[0]['company_name']} ({jobs[0]['status']})")
