apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recruitment-platform.fullname" . }}-config
  labels:
    {{- include "recruitment-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
