apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recruitment-platform.fullname" . }}-secrets
  labels:
    {{- include "recruitment-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
