apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recruitment-platform-development

resources:
  - ../../base

namePrefix: development-

patches:
  - target:
      kind: Deployment
      name: recruitment-platform
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
