"""Recruitment Platform Python SDK.

A production-grade Python client for the Recruitment Platform REST API.
Provides typed access to all 42 endpoints across 10 recruitment domains
with automatic retries, rate limiting, caching, and comprehensive error handling.

Supports both synchronous and asynchronous usage:
- RecruitmentPlatformClient: synchronous client
- AsyncRecruitmentPlatformClient: asynchronous client with full async/await support
"""

from .async_client import AsyncRecruitmentPlatformClient
from .cache import RedisCache
from .client import RecruitmentPlatformClient
from .exceptions import (
    AuthenticationError,
    CacheError,
    CircuitBreakerOpenError,
    ConfigurationError,
    ConnectionError,
    NotFoundError,
    RateLimitError,
    RecruitmentPlatformError,
    ServerError,
    TimeoutError,
    ValidationError,
)
from .logging_config import (
    clear_correlation_id,
    get_correlation_id,
    get_logger,
    log_error,
    log_performance,
    log_request,
    set_correlation_id,
    setup_logging,
)
from .models import (
    HealthResponse,
    APIResponse,
    ResumeParseRequest,
    ResumeParseResponse,
    ContactExtractionRequest,
    ContactExtractionResponse,
    SkillsExtractionRequest,
    SkillsExtractionResponse,
    CandidateMatchRequest,
    CandidateMatchResponse,
    MatchExplanationRequest,
    MatchExplanationResponse,
    GapAnalysisRequest,
    GapAnalysisResponse,
    InterviewSlotRequest,
    InterviewSlotResponse,
    ConflictDetectionRequest,
    ConflictDetectionResponse,
    ReminderRequest,
    ReminderResponse,
    SkillsAssessmentRequest,
    SkillsAssessmentResponse,
    LearningPathRequest,
    LearningPathResponse,
    SkillValidationRequest,
    SkillValidationResponse,
    BiasLanguageRequest,
    BiasLanguageResponse,
    FairnessScoreRequest,
    FairnessScoreResponse,
    DemographicAnalysisRequest,
    DemographicAnalysisResponse,
    BiasRecommendationRequest,
    BiasRecommendationResponse,
    TalentSourceRequest,
    TalentSourceResponse,
    PoolAnalysisRequest,
    PoolAnalysisResponse,
    TalentRecommendRequest,
    TalentRecommendResponse,
    EngagementTrackRequest,
    EngagementTrackResponse,
    CostAnalysisRequest,
    CostAnalysisResponse,
    FunnelAnalysisRequest,
    FunnelAnalysisResponse,
    DiversityMetricsRequest,
    DiversityMetricsResponse,
    HiringPredictionRequest,
    HiringPredictionResponse,
    SourceEffectivenessRequest,
    SourceEffectivenessResponse,
    ComplianceCheckRequest,
    ComplianceCheckResponse,
    DocumentGenerationRequest,
    DocumentGenerationResponse,
    ProgressTrackRequest,
    ProgressTrackResponse,
    TaskScheduleRequest,
    TaskScheduleResponse,
    WelcomeMessageRequest,
    WelcomeMessageResponse,
    ATSCompatibilityRequest,
    ATSCompatibilityResponse,
    BiasRemovalRequest,
    BiasRemovalResponse,
    KeywordOptimizationRequest,
    KeywordOptimizationResponse,
    SEOOptimizationRequest,
    SEOOptimizationResponse,
    ToneAnalysisRequest,
    ToneAnalysisResponse,
    BrandStrategyRequest,
    BrandStrategyResponse,
    ContentGenerationRequest,
    ContentGenerationResponse,
    ReputationManagementRequest,
    ReputationManagementResponse,
    ReviewAnalysisRequest,
    ReviewAnalysisResponse,
    SentimentAnalysisRequest,
    SentimentAnalysisResponse,
)
from .rate_limiter import AsyncTokenBucketRateLimiter, TokenBucketRateLimiter

__version__ = "2.0.0"
__author__ = "Ahmed Hassan"
__license__ = "MIT"

__all__ = [
    # Clients
    "RecruitmentPlatformClient",
    "AsyncRecruitmentPlatformClient",
    # Exceptions
    "RecruitmentPlatformError",
    "AuthenticationError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "ValidationError",
    "TimeoutError",
    "ConnectionError",
    "CacheError",
    "ConfigurationError",
    "CircuitBreakerOpenError",
    # Models
    "HealthResponse",
    "APIResponse",
    "ResumeParseRequest",
    "ResumeParseResponse",
    "ContactExtractionRequest",
    "ContactExtractionResponse",
    "SkillsExtractionRequest",
    "SkillsExtractionResponse",
    "CandidateMatchRequest",
    "CandidateMatchResponse",
    "MatchExplanationRequest",
    "MatchExplanationResponse",
    "GapAnalysisRequest",
    "GapAnalysisResponse",
    "InterviewSlotRequest",
    "InterviewSlotResponse",
    "ConflictDetectionRequest",
    "ConflictDetectionResponse",
    "ReminderRequest",
    "ReminderResponse",
    "SkillsAssessmentRequest",
    "SkillsAssessmentResponse",
    "LearningPathRequest",
    "LearningPathResponse",
    "SkillValidationRequest",
    "SkillValidationResponse",
    "BiasLanguageRequest",
    "BiasLanguageResponse",
    "FairnessScoreRequest",
    "FairnessScoreResponse",
    "DemographicAnalysisRequest",
    "DemographicAnalysisResponse",
    "BiasRecommendationRequest",
    "BiasRecommendationResponse",
    "TalentSourceRequest",
    "TalentSourceResponse",
    "PoolAnalysisRequest",
    "PoolAnalysisResponse",
    "TalentRecommendRequest",
    "TalentRecommendResponse",
    "EngagementTrackRequest",
    "EngagementTrackResponse",
    "CostAnalysisRequest",
    "CostAnalysisResponse",
    "FunnelAnalysisRequest",
    "FunnelAnalysisResponse",
    "DiversityMetricsRequest",
    "DiversityMetricsResponse",
    "HiringPredictionRequest",
    "HiringPredictionResponse",
    "SourceEffectivenessRequest",
    "SourceEffectivenessResponse",
    "ComplianceCheckRequest",
    "ComplianceCheckResponse",
    "DocumentGenerationRequest",
    "DocumentGenerationResponse",
    "ProgressTrackRequest",
    "ProgressTrackResponse",
    "TaskScheduleRequest",
    "TaskScheduleResponse",
    "WelcomeMessageRequest",
    "WelcomeMessageResponse",
    "ATSCompatibilityRequest",
    "ATSCompatibilityResponse",
    "BiasRemovalRequest",
    "BiasRemovalResponse",
    "KeywordOptimizationRequest",
    "KeywordOptimizationResponse",
    "SEOOptimizationRequest",
    "SEOOptimizationResponse",
    "ToneAnalysisRequest",
    "ToneAnalysisResponse",
    "BrandStrategyRequest",
    "BrandStrategyResponse",
    "ContentGenerationRequest",
    "ContentGenerationResponse",
    "ReputationManagementRequest",
    "ReputationManagementResponse",
    "ReviewAnalysisRequest",
    "ReviewAnalysisResponse",
    "SentimentAnalysisRequest",
    "SentimentAnalysisResponse",
    # Rate Limiting
    "TokenBucketRateLimiter",
    "AsyncTokenBucketRateLimiter",
    # Caching
    "RedisCache",
    # Logging
    "get_logger",
    "setup_logging",
    "log_request",
    "log_error",
    "log_performance",
]
